Build tool update
Modifications to gulp task to include TypeScript compilation once more but now
catches errors and throws notifications up accordingly. This eliminates the
need for an external dependency for TS compilation as it can now be handled all
by using `gulp compile-js`

diff --git a/gulpfile.js b/gulpfile.js
index 5ce4169..4d6a696 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -1,5 +1,6 @@
 var gulp = require('gulp');
 var notify = require('gulp-notify');
+var plumber = require('gulp-plumber');

 /*
  * Browserify/watchify bundler stuff
@@ -14,7 +15,7 @@ var jsConfig = {
   publicPath : __dirname + '/javascript/dist',
   source: {
     path: __dirname + '/javascript/src',
-    main: 'woocommerce-cc-gateway.js',
+    main: 'woocommerce-cc-gateway.ts',
     result: 'woocommerce-cc-gateway.js'
   }
 };
@@ -27,12 +28,22 @@ gulp.task('compile-js', function (){
       packageCache: {}
     })
     .add(jsConfig.source.path + '/' + jsConfig.source.main)
-    // .plugin(tsify);
+    .plugin(tsify);

   bundler = watchify(bundler);

   var bundle = function(bundler){
     bundler.bundle()
+      .on('error', notify.onError({
+        message: 'Error: <%= error.toString() %>',
+        title: 'Compile Error',
+        sound: true,
+        icon: ''
+      }))
+      .on('error', function(error){
+        this.emit('end');
+      })
+      .pipe(plumber({errorHandler: notify.onError("Error: <%= error.message %>")}))
       .pipe(source(jsConfig.source.result))
       .pipe(gulp.dest(jsConfig.publicPath))
       .pipe(notify('Bundle re-bundled.'));
diff --git a/javascript/dist/woocommerce-cc-gateway.js b/javascript/dist/woocommerce-cc-gateway.js
index 73778ba..50d0216 100644
--- a/javascript/dist/woocommerce-cc-gateway.js
+++ b/javascript/dist/woocommerce-cc-gateway.js
@@ -1,138 +1,3 @@
 (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
-var WoocommereCardConnect = (function () {
-    function WoocommereCardConnect(jQuery, csApiEndpoint) {
-        var _this = this;
-        this.getToken = function (number, callback) {
-            if (!_this.validateCard(number))
-                return callback(null, 'Invalid Credit Card Number');
-            _this.$.get(_this.baseUrl + "&data=" + _this.cardNumber)
-                .done(function (data) { return _this.processRequest(data, callback); })
-                .fail(function (data) { return _this.failedRequest(data, callback); });
-        };
-        this.validateCard = function (number) {
-            _this.cardNumber = number;
-            if (_this.$.payment) {
-                return _this.$.payment.validateCardNumber(_this.cardNumber);
-            }
-            else {
-                return _this.cardNumber.length > 0;
-            }
-        };
-        this.processRequest = function (data, callback) {
-            var processToken = function (response) {
-                var action = response.action, data = response.data;
-                if (action === 'CE')
-                    callback(data, null);
-                else
-                    callback(null, data);
-            };
-            eval(data);
-        };
-        this.failedRequest = function (data, callback) {
-            return callback(null, 'Failed to connect to server');
-        };
-        this.$ = jQuery;
-        this.baseUrl = csApiEndpoint + '?action=CE&type=json';
-    }
-    return WoocommereCardConnect;
-})();
-exports.default = WoocommereCardConnect;

-},{}],2:[function(require,module,exports){
-/// <reference path="./typings/tsd.d.ts"/>
-var woocommerce_card_connect_1 = require("./woocommerce-card-connect");
-jQuery(function ($) {
-    var isLive = Boolean(wooCardConnect.isLive);
-    var cc = new woocommerce_card_connect_1.default($, wooCardConnect.apiEndpoint);
-    var $form = $('form.checkout, form#order_review');
-    var $errors;
-    if (!isLive) {
-        $('body').on('updated_checkout', function () {
-            getToken();
-        });
-    }
-    function getToken() {
-        if (checkAllowSubmit())
-            return false;
-        var $ccInput = $form.find('#card_connect-card-number');
-        var creditCard = $ccInput.val();
-        $form.block({
-            message: null,
-            overlayCSS: {
-                background: '#fff',
-                opacity: 0.6
-            }
-        });
-        if (!creditCard) {
-            printWooError('Please enter a credit card number');
-            return false;
-        }
-        else if (!checkCardType(creditCard)) {
-            printWooError('Credit card type not accepted');
-            return false;
-        }
-        cc.getToken(creditCard, function (token, error) {
-            if (error) {
-                printWooError(error);
-                return false;
-            }
-            $('<input />')
-                .attr('name', 'card_connect_token')
-                .attr('type', 'hidden')
-                .addClass('card-connect-token')
-                .val(token)
-                .appendTo($form);
-            $ccInput.val($.map(creditCard.split(''), function (char, index) {
-                if (creditCard.length - (index + 1) > 4) {
-                    return char !== ' ' ? '\u2022' : ' ';
-                }
-                else {
-                    return char;
-                }
-            }).join(''));
-        });
-        $form.unblock();
-        return true;
-    }
-    function checkAllowSubmit() {
-        return 0 !== $('input.card-connect-token', $form).size();
-    }
-    function checkCardType(cardNumber) {
-        var cardType = $.payment.cardType(cardNumber);
-        for (var i = 0; i < wooCardConnect.allowedCards.length; i++) {
-            if (wooCardConnect.allowedCards[i] === cardType)
-                return true;
-        }
-        return false;
-    }
-    function printWooError(error) {
-        if (!$errors)
-            $errors = $('.js-card-connect-errors', $form);
-        var errorText;
-        if (error.constructor === Array) {
-            errorText = Array(error).reduce(function (prev, curr) { return prev += "<li>" + curr + "</li>"; });
-        }
-        else {
-            errorText = "<li>" + error + "</li>";
-        }
-        $errors.html("<ul class=\"woocommerce-error\">" + errorText + "</ul>");
-        $form.unblock();
-    }
-    $form.on('blur', '#card_connect-card-number', function () {
-        if ($errors)
-            $errors.html('');
-        return getToken();
-    });
-    $form.on('checkout_place_order_card_connect', function () { return checkAllowSubmit(); });
-    $('form#order_review').on('submit', function () { return checkAllowSubmit(); });
-    $('document.body').on('checkout_error', function () {
-        if ($errors)
-            $errors.html('');
-        $('.card-connect-token').remove();
-    });
-    $form.on('keyup change', '#card_connect-card-number', function () {
-        $('.card-connect-token').remove();
-    });
-});
-
-},{"./woocommerce-card-connect":1}]},{},[2]);
+},{}]},{},[1]);
diff --git a/javascript/src/woocommerce-card-connect.js b/javascript/src/woocommerce-card-connect.js
deleted file mode 100644
index 5abc5de..0000000
--- a/javascript/src/woocommerce-card-connect.js
+++ /dev/null
@@ -1,38 +0,0 @@
-var WoocommereCardConnect = (function () {
-    function WoocommereCardConnect(jQuery, csApiEndpoint) {
-        var _this = this;
-        this.getToken = function (number, callback) {
-            if (!_this.validateCard(number))
-                return callback(null, 'Invalid Credit Card Number');
-            _this.$.get(_this.baseUrl + "&data=" + _this.cardNumber)
-                .done(function (data) { return _this.processRequest(data, callback); })
-                .fail(function (data) { return _this.failedRequest(data, callback); });
-        };
-        this.validateCard = function (number) {
-            _this.cardNumber = number;
-            if (_this.$.payment) {
-                return _this.$.payment.validateCardNumber(_this.cardNumber);
-            }
-            else {
-                return _this.cardNumber.length > 0;
-            }
-        };
-        this.processRequest = function (data, callback) {
-            var processToken = function (response) {
-                var action = response.action, data = response.data;
-                if (action === 'CE')
-                    callback(data, null);
-                else
-                    callback(null, data);
-            };
-            eval(data);
-        };
-        this.failedRequest = function (data, callback) {
-            return callback(null, 'Failed to connect to server');
-        };
-        this.$ = jQuery;
-        this.baseUrl = csApiEndpoint + '?action=CE&type=json';
-    }
-    return WoocommereCardConnect;
-})();
-exports.default = WoocommereCardConnect;
diff --git a/javascript/src/woocommerce-cc-gateway.js b/javascript/src/woocommerce-cc-gateway.js
deleted file mode 100644
index f43cd2c..0000000
--- a/javascript/src/woocommerce-cc-gateway.js
+++ /dev/null
@@ -1,95 +0,0 @@
-/// <reference path="./typings/tsd.d.ts"/>
-var woocommerce_card_connect_1 = require("./woocommerce-card-connect");
-jQuery(function ($) {
-    var isLive = Boolean(wooCardConnect.isLive);
-    var cc = new woocommerce_card_connect_1.default($, wooCardConnect.apiEndpoint);
-    var $form = $('form.checkout, form#order_review');
-    var $errors;
-    if (!isLive) {
-        $('body').on('updated_checkout', function () {
-            getToken();
-        });
-    }
-    function getToken() {
-        if (checkAllowSubmit())
-            return false;
-        var $ccInput = $form.find('#card_connect-card-number');
-        var creditCard = $ccInput.val();
-        $form.block({
-            message: null,
-            overlayCSS: {
-                background: '#fff',
-                opacity: 0.6
-            }
-        });
-        if (!creditCard) {
-            printWooError('Please enter a credit card number');
-            return false;
-        }
-        else if (!checkCardType(creditCard)) {
-            printWooError('Credit card type not accepted');
-            return false;
-        }
-        cc.getToken(creditCard, function (token, error) {
-            if (error) {
-                printWooError(error);
-                return false;
-            }
-            $('<input />')
-                .attr('name', 'card_connect_token')
-                .attr('type', 'hidden')
-                .addClass('card-connect-token')
-                .val(token)
-                .appendTo($form);
-            $ccInput.val($.map(creditCard.split(''), function (char, index) {
-                if (creditCard.length - (index + 1) > 4) {
-                    return char !== ' ' ? '\u2022' : ' ';
-                }
-                else {
-                    return char;
-                }
-            }).join(''));
-        });
-        $form.unblock();
-        return true;
-    }
-    function checkAllowSubmit() {
-        return 0 !== $('input.card-connect-token', $form).size();
-    }
-    function checkCardType(cardNumber) {
-        var cardType = $.payment.cardType(cardNumber);
-        for (var i = 0; i < wooCardConnect.allowedCards.length; i++) {
-            if (wooCardConnect.allowedCards[i] === cardType)
-                return true;
-        }
-        return false;
-    }
-    function printWooError(error) {
-        if (!$errors)
-            $errors = $('.js-card-connect-errors', $form);
-        var errorText;
-        if (error.constructor === Array) {
-            errorText = Array(error).reduce(function (prev, curr) { return prev += "<li>" + curr + "</li>"; });
-        }
-        else {
-            errorText = "<li>" + error + "</li>";
-        }
-        $errors.html("<ul class=\"woocommerce-error\">" + errorText + "</ul>");
-        $form.unblock();
-    }
-    $form.on('blur', '#card_connect-card-number', function () {
-        if ($errors)
-            $errors.html('');
-        return getToken();
-    });
-    $form.on('checkout_place_order_card_connect', function () { return checkAllowSubmit(); });
-    $('form#order_review').on('submit', function () { return checkAllowSubmit(); });
-    $('document.body').on('checkout_error', function () {
-        if ($errors)
-            $errors.html('');
-        $('.card-connect-token').remove();
-    });
-    $form.on('keyup change', '#card_connect-card-number', function () {
-        $('.card-connect-token').remove();
-    });
-});
diff --git a/package.json b/package.json
index 783060e..18e8eb0 100644
--- a/package.json
+++ b/package.json
@@ -15,6 +15,7 @@
     "gulp-if": "^1.2.5",
     "gulp-ignore": "^1.2.1",
     "gulp-notify": "^2.2.0",
+    "gulp-plumber": "^1.0.0",
     "gulp-uglify": "^1.2.0",
     "mocha": "^2.2.1",
     "tsify": "dpogue/tsify#ts1.5-alpha",